In [3]:
from statsbombpy import sb
import warnings
import pandas as pd

from datadownloader import DataDownloader
from datasetcreator import columns_to_keep, DataSetCreator

# Download all games

In [4]:
# Call statsbombpy API to get all free competitions
free_comps = sb.competitions()
free_comps.head()

c:\Users\kwvanarem\Documents\GitHub\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-07-15T14:15:54.671676,2024-07-15T14:17:00.877356,2024-07-15T14:17:00.877356,2024-07-15T14:15:54.671676
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-06-13T07:51:02.452825,None,None,2024-06-13T07:51:02.452825
3,16,4,Europe,Champions League,male,False,False,2018/2019,2024-06-12T07:44:38.559714,2021-06-13T16:17:31.694,None,2024-06-12T07:44:38.559714
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [5]:
free_comps

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-07-15T14:15:54.671676,2024-07-15T14:17:00.877356,2024-07-15T14:17:00.877356,2024-07-15T14:15:54.671676
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-06-13T07:51:02.452825,None,None,2024-06-13T07:51:02.452825
3,16,4,Europe,Champions League,male,False,False,2018/2019,2024-06-12T07:44:38.559714,2021-06-13T16:17:31.694,None,2024-06-12T07:44:38.559714
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
69,55,43,Europe,UEFA Euro,male,False,True,2020,2024-04-16T12:44:40.558402,2024-04-16T12:47:18.505110,2024-04-16T12:47:18.505110,2024-04-16T12:44:40.558402
70,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2024-02-12T14:45:05.702250,2021-06-13T16:17:31.694,None,2024-02-12T14:45:05.702250
71,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2024-02-13T13:27:17.178263,2024-02-13T13:30:52.820588,2024-02-13T13:30:52.820588,2024-02-13T13:27:17.178263
72,72,107,International,Women's World Cup,female,False,True,2023,2024-07-14T16:59:48.469596,2024-07-14T17:01:38.887279,2024-07-14T17:01:38.887279,2024-07-14T16:59:48.469596
73,72,30,International,Women's World Cup,female,False,True,2019,2024-02-13T09:41:26.379767,2021-06-13T16:17:31.694,None,2024-02-13T09:41:26.379767

In [6]:
free_comps['competition_name'].unique().tolist()

['1. Bundesliga',
 'African Cup of Nations',
 'Champions League',
 'Copa America',
 'Copa del Rey',
 "FA Women's Super League",
 'FIFA U20 World Cup',
 'FIFA World Cup',
 'Indian Super league',
 'La Liga',
 'Liga Profesional',
 'Ligue 1',
 'Major League Soccer',
 'North American League',
 'NWSL',
 'Premier League',
 'Serie A',
 'UEFA Euro',
 'UEFA Europa League',
 "UEFA Women's Euro",
 "Women's World Cup"]

In [7]:
competition_ids = [
    11, # LaLiga
    2, # Premier League
    12, # Serie A
    7, # Ligue 1
    9, # Bundesliga
]

In [9]:
warnings.filterwarnings("ignore", message="credentials were not supplied")
for competition_id in competition_ids:
    free_seasons = free_comps[free_comps['competition_id'] == competition_id]
    downloader = DataDownloader(free_seasons, directory='.\\data-storage\\raw_data')
    downloader.download_store_seasons()

2020_2021

100%|██████████| 35/35 [00:17<00:00,  1.97it/s]

Downloaded, processed, and stored all available events of La Liga (2020/2021) in 0.30 minutes.
2019_2020

100%|██████████| 33/33 [00:21<00:00,  1.51it/s]

Downloaded, processed, and stored all available events of La Liga (2019/2020) in 0.37 minutes.
2018_2019

100%|██████████| 34/34 [00:20<00:00,  1.63it/s]

Downloaded, processed, and stored all available events of La Liga (2018/2019) in 0.35 minutes.
2017_2018

100%|██████████| 36/36 [00:20<00:00,  1.79it/s]

Downloaded, processed, and stored all available events of La Liga (2017/2018) in 0.34 minutes.
2016_2017

100%|██████████| 34/34 [00:16<00:00,  2.04it/s]

Downloaded, processed, and stored all available events of La Liga (2016/2017) in 0.28 minutes.
2015_2016

100%|██████████| 380/380 [03:06<00:00,  2.04it/s]

Downloaded, processed, and stored all available events of La Liga (2015/2016) in 3.11 minutes.
2014_2015

100%|██████████| 38/38 [00:21<00:00,  1.74it/s]

Downloaded, processed, and stored all available events of La Liga (2014/2015) in 0.37 minutes.
2013_2014

100%|██████████| 31/31 [00:18<00:00,  1.71it/s]

Downloaded, processed, and stored all available events of La Liga (2013/2014) in 0.31 minutes.
2012_2013

100%|██████████| 32/32 [00:15<00:00,  2.10it/s]

Downloaded, processed, and stored all available events of La Liga (2012/2013) in 0.26 minutes.
2011_2012

100%|██████████| 37/37 [00:17<00:00,  2.15it/s]

Downloaded, processed, and stored all available events of La Liga (2011/2012) in 0.29 minutes.
2010_2011

100%|██████████| 33/33 [00:14<00:00,  2.23it/s]

Downloaded, processed, and stored all available events of La Liga (2010/2011) in 0.25 minutes.
2009_2010

100%|██████████| 35/35 [00:16<00:00,  2.16it/s]

Downloaded, processed, and stored all available events of La Liga (2009/2010) in 0.27 minutes.
2008_2009

100%|██████████| 31/31 [00:13<00:00,  2.30it/s]

Downloaded, processed, and stored all available events of La Liga (2008/2009) in 0.23 minutes.
2007_2008

100%|██████████| 28/28 [00:12<00:00,  2.22it/s]

Downloaded, processed, and stored all available events of La Liga (2007/2008) in 0.21 minutes.
2006_2007

100%|██████████| 26/26 [00:11<00:00,  2.27it/s]

Downloaded, processed, and stored all available events of La Liga (2006/2007) in 0.19 minutes.
2005_2006

100%|██████████| 17/17 [00:07<00:00,  2.34it/s]

Downloaded, processed, and stored all available events of La Liga (2005/2006) in 0.12 minutes.
2004_2005

100%|██████████| 7/7 [00:02<00:00,  2.50it/s]

Downloaded, processed, and stored all available events of La Liga (2004/2005) in 0.05 minutes.
1973_1974

100%|██████████| 1/1 [00:00<00:00,  2.12it/s]

Downloaded, processed, and stored all available events of La Liga (1973/1974) in 0.01 minutes.
2015_2016

 91%|█████████ | 346/380 [03:07<00:18,  1.84it/s]

HTTPError: 429 Client Error: Too Many Requests for url: https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/3754268.json

In [ ]:
# Select UEFA Euros 2020
free_seasons = free_comps[free_comps['season_id'] == 43]
downloader = DataDownloader(free_seasons, directory='.\\data-storage\\raw_data_euros2020')
downloader.download_store_seasons()

2020

  0%|          | 0/51 [00:00<?, ?it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
  2%|▏         | 1/51 [00:00<00:17,  2.92it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
  4%|▍         | 2/51 [00:00<00:16,  2.90it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
  6%|▌         | 3/51 [00:00<00:14,  3.21it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
  8%|▊         | 4/51 [00:01<00:12,  3.70it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 10%|▉         | 5/51 [00:01<00:11,  4.15it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 12%|█▏        | 6/51 [00:01<00:12,  3.57it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 14%|█▎        | 7/51 [00:01<00:10,  4.21it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 16%|█▌        | 8/51 [00:02<00:10,  4.27it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 18%|█▊        | 9/51 [00:02<00:10,  3.98it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 20%|█▉        | 10/51 [00:02<00:12,  3.26it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 22%|██▏       | 11/51 [00:03<00:12,  3.19it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 24%|██▎       | 12/51 [00:03<00:11,  3.44it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 25%|██▌       | 13/51 [00:03<00:11,  3.39it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 27%|██▋       | 14/51 [00:04<00:12,  2.93it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 29%|██▉       | 15/51 [00:04<00:11,  3.18it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 31%|███▏      | 16/51 [00:04<00:11,  3.13it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 33%|███▎      | 17/51 [00:05<00:10,  3.12it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 35%|███▌      | 18/51 [00:05<00:09,  3.42it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 37%|███▋      | 19/51 [00:05<00:08,  3.71it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 39%|███▉      | 20/51 [00:05<00:08,  3.80it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 41%|████      | 21/51 [00:06<00:11,  2.64it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 43%|████▎     | 22/51 [00:07<00:13,  2.08it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 45%|████▌     | 23/51 [00:07<00:13,  2.04it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 47%|████▋     | 24/51 [00:08<00:14,  1.89it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 49%|████▉     | 25/51 [00:08<00:14,  1.80it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 51%|█████     | 26/51 [00:09<00:13,  1.81it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 53%|█████▎    | 27/51 [00:09<00:13,  1.84it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 55%|█████▍    | 28/51 [00:10<00:12,  1.87it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 57%|█████▋    | 29/51 [00:10<00:11,  1.87it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 59%|█████▉    | 30/51 [00:11<00:11,  1.81it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 61%|██████    | 31/51 [00:12<00:10,  1.82it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 63%|██████▎   | 32/51 [00:12<00:10,  1.86it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 65%|██████▍   | 33/51 [00:13<00:09,  1.90it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 67%|██████▋   | 34/51 [00:13<00:09,  1.85it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 69%|██████▊   | 35/51 [00:14<00:09,  1.77it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 71%|███████   | 36/51 [00:14<00:08,  1.79it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 73%|███████▎  | 37/51 [00:15<00:08,  1.70it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 75%|███████▍  | 38/51 [00:16<00:07,  1.67it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 76%|███████▋  | 39/51 [00:16<00:07,  1.58it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 78%|███████▊  | 40/51 [00:17<00:06,  1.60it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 80%|████████  | 41/51 [00:18<00:06,  1.59it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 82%|████████▏ | 42/51 [00:18<00:05,  1.54it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 84%|████████▍ | 43/51 [00:19<00:05,  1.47it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 86%|████████▋ | 44/51 [00:20<00:04,  1.52it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 88%|████████▊ | 45/51 [00:20<00:03,  1.54it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 90%|█████████ | 46/51 [00:21<00:03,  1.59it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 92%|█████████▏| 47/51 [00:21<00:02,  1.61it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 94%|█████████▍| 48/51 [00:22<00:01,  1.70it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 96%|█████████▌| 49/51 [00:23<00:01,  1.70it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
 98%|█████████▊| 50/51 [00:23<00:00,  1.48it/s]c:\Users\kwvanarem\Documents\Onderzoek\xthreat-error-quantification\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
100%|██████████| 51/51 [00:24<00:00,  2.08it/s]

Downloaded, processed, and stored all available events of UEFA Euro (2020) in 0.41 minutes.

# Create data set

In [ ]:
# data_set_creator = DataSetCreator(
#     ['type', 'x', 'y', 'under_pressure', 'team_id', 'player_id'],
#     storage_directory='./',
# )
# data_set_creator.create_data_set('./data-storage/raw_data/', 'extra_filtered_data.parquet')

Processing files:   0%|          | 0/2442 [00:00<?, ?it/s]

Processing files: 100%|██████████| 2442/2442 [20:06<00:00,  2.02it/s]

In [ ]:
# data_set_creator = DataSetCreator(
#     ['type', 'x', 'y', 'under_pressure', 'team_id', 'player_id'],
#     storage_directory='./',
# )
# data_set_creator.create_data_set('./data-storage/raw_data/', 'test.parquet')

Processing files: 100%|██████████| 2442/2442 [5:49:41<00:00,  8.59s/it]

In [ ]:
data_path_data_set = './data-storage/xThreat_data_v3.parquet'

In [ ]:
data_set_creator = DataSetCreator(
    ['type', 'x', 'y', 'under_pressure', 'team_id', 'player_id'],
    storage_directory='./',
)
data_set_creator.create_data_set('./data-storage/raw_data/', data_path_data_set)

Processing files:   0%|          | 0/2442 [00:00<?, ?it/s]

Processing files: 100%|██████████| 2442/2442 [20:46<00:00,  1.96it/s]

Should be 2442

In [ ]:
df_events = pd.read_parquet(data_path_data_set, engine='fastparquet')

df_events['shot'] = ~df_events['shot_outcome'].isna()
df_events['goal'] = df_events['shot_outcome'] == 'Goal'

df_events.drop(columns=['id', 'shot_outcome', 'possession'], inplace=True)
df_size_bytes = df_events.memory_usage(deep=True).sum()
df_size_mb = df_size_bytes / (1024 ** 2)  # Convert to MB
print(f"DataFrame size: {df_size_mb:.2f} MB")
print(f"DataFrame shape: {df_events.shape}")

del df_events

DataFrame size: 999.40 MB
DataFrame shape: (4038776, 21)

In [ ]:
# df_events = pd.read_parquet('extra_filtered_data.parquet', engine='fastparquet')

# df_events['shot'] = ~df_events['shot_outcome'].isna()
# df_events['goal'] = df_events['shot_outcome'] == 'Goal'

# df_events.drop(columns=['id', 'shot_outcome', 'possession'], inplace=True)
# df_size_bytes = df_events.memory_usage(deep=True).sum()
# df_size_mb = df_size_bytes / (1024 ** 2)  # Convert to MB
# print(f"DataFrame size: {df_size_mb:.2f} MB")
# print(f"DataFrame shape: {df_events.shape}")

DataFrame size: 1039.54 MB
DataFrame shape: (3985659, 21)

In [ ]:
# df_events.isna().sum()

x                            0
y                            0
possession_kept              0
possession_length            0
chain_length                 0
previous_deleted             0
match_id                     0
period                       0
player_id                    0
type                         0
shot_statsbomb_xg      3956799
pass_height            1911526
under_pressure         2963142
next_type                    0
next_x                       0
next_y                       0
next_under_pressure    2962808
next_team_id                 0
next_player_id               0
shot                         0
goal                         0
dtype: int64

In [ ]:
data_set_creator = DataSetCreator(
    ['type', 'x', 'y', 'under_pressure', 'team_id', 'player_id'],
    storage_directory='./',
)
data_set_creator.create_data_set('./data-storage/raw_data_euros2020/', './data-storage/xThreat_data_v3_euros2020.parquet')

Processing files: 100%|██████████| 51/51 [00:20<00:00,  2.47it/s]